version: 1.0
provider:
  name: openfaas
  gateway: http://20.26.125.107:8080
functions:
  hello-vin-python:
    lang: python3-http-debian
    handler: ./hello-vin-python
    image: vindhyaasaravanan2003/hello-vin-python:latest

  process-image:
    lang: python3-http-debian
    handler: ./process-image
    image: vindhyaasaravanan2003/process-image:latest
    labels:
      com.openfaas.scale.zero: "true"

